"""initial_schema

Revision ID: 87154d074e49
Revises: 
Create Date: 2026-09-20 18:20:21.576996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87154d074e49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('contributing_signals', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_alerts_entity_type'), 'alerts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('asn_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country_count', sa.Integer(), nullable=True),
    sa.Column('ip_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asn_entities_asn_number'), 'asn_entities', ['asn_number'], unique=True)
    op.create_index(op.f('ix_asn_entities_id'), 'asn_entities', ['id'], unique=False)
    op.create_table('behavioral_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('feature_schema_version', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_features_entity_id'), 'behavioral_features', ['entity_id'], unique=False)
    op.create_index(op.f('ix_behavioral_features_entity_type'), 'behavioral_features', ['entity_type'], unique=False)
    op.create_index(op.f('ix_behavioral_features_id'), 'behavioral_features', ['id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('valid_records', sa.Integer(), nullable=True),
    sa.Column('invalid_records', sa.Integer(), nullable=True),
    sa.Column('duplicate_records', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_entity_id'), 'evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_entity_type'), 'evidence', ['entity_type'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('edge_type', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_id'), 'graph_edges', ['id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_id'), 'graph_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_node_id'), 'graph_nodes', ['node_id'], unique=False)
    op.create_table('ip_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_entities_id'), 'ip_entities', ['id'], unique=False)
    op.create_index(op.f('ix_ip_entities_ip_address'), 'ip_entities', ['ip_address'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_sent', sa.Float(), nullable=True),
    sa.Column('total_received', sa.Float(), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('investigator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('feature_schema_version', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('training_timestamp', sa.DateTime(), nullable=True),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_id'), 'model_runs', ['id'], unique=False)
    op.create_table('network_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('geo_country', sa.String(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_observations_id'), 'network_observations', ['id'], unique=False)
    op.create_index(op.f('ix_network_observations_src_ip'), 'network_observations', ['src_ip'], unique=False)
    op.create_index(op.f('ix_network_observations_transaction_id'), 'network_observations', ['transaction_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_id'), 'raw_records', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('txid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('script_type', sa.String(), nullable=True),
    sa.Column('total_input', sa.Float(), nullable=True),
    sa.Column('total_output', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_txid'), 'transactions', ['txid'], unique=True)
    op.create_table('anomaly_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_results_entity_id'), 'anomaly_results', ['entity_id'], unique=False)
    op.create_index(op.f('ix_anomaly_results_entity_type'), 'anomaly_results', ['entity_type'], unique=False)
    op.create_index(op.f('ix_anomaly_results_id'), 'anomaly_results', ['id'], unique=False)
    op.create_table('case_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_entities_id'), 'case_entities', ['id'], unique=False)
    op.create_table('case_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_evidence_id'), 'case_evidence', ['id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_id'), 'case_notes', ['id'], unique=False)
    op.create_table('transaction_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_inputs_id'), 'transaction_inputs', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_inputs_wallet_address'), 'transaction_inputs', ['wallet_address'], unique=False)
    op.create_table('transaction_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_outputs_id'), 'transaction_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_outputs_wallet_address'), 'transaction_outputs', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_outputs_wallet_address'), table_name='transaction_outputs')
    op.drop_index(op.f('ix_transaction_outputs_id'), table_name='transaction_outputs')
    op.drop_table('transaction_outputs')
    op.drop_index(op.f('ix_transaction_inputs_wallet_address'), table_name='transaction_inputs')
    op.drop_index(op.f('ix_transaction_inputs_id'), table_name='transaction_inputs')
    op.drop_table('transaction_inputs')
    op.drop_index(op.f('ix_case_notes_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_evidence_id'), table_name='case_evidence')
    op.drop_table('case_evidence')
    op.drop_index(op.f('ix_case_entities_id'), table_name='case_entities')
    op.drop_table('case_entities')
    op.drop_index(op.f('ix_anomaly_results_id'), table_name='anomaly_results')
    op.drop_index(op.f('ix_anomaly_results_entity_type'), table_name='anomaly_results')
    op.drop_index(op.f('ix_anomaly_results_entity_id'), table_name='anomaly_results')
    op.drop_table('anomaly_results')
    op.drop_index(op.f('ix_transactions_txid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_raw_records_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_network_observations_transaction_id'), table_name='network_observations')
    op.drop_index(op.f('ix_network_observations_src_ip'), table_name='network_observations')
    op.drop_index(op.f('ix_network_observations_id'), table_name='network_observations')
    op.drop_table('network_observations')
    op.drop_index(op.f('ix_model_runs_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ip_entities_ip_address'), table_name='ip_entities')
    op.drop_index(op.f('ix_ip_entities_id'), table_name='ip_entities')
    op.drop_table('ip_entities')
    op.drop_index(op.f('ix_graph_nodes_node_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_graph_edges_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_entity_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_entity_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_behavioral_features_id'), table_name='behavioral_features')
    op.drop_index(op.f('ix_behavioral_features_entity_type'), table_name='behavioral_features')
    op.drop_index(op.f('ix_behavioral_features_entity_id'), table_name='behavioral_features')
    op.drop_table('behavioral_features')
    op.drop_index(op.f('ix_asn_entities_id'), table_name='asn_entities')
    op.drop_index(op.f('ix_asn_entities_asn_number'), table_name='asn_entities')
    op.drop_table('asn_entities')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
