import { Link } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { ShieldCheck, FileText, ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
        <Link to="/" className="hover:text-slate-200 flex items-center gap-1">
          <ArrowLeft size={12} /> Command Center
        </Link>
        <span>/</span>
        <span className="text-slate-300">Terms of Service</span>
      </div>

      <PageHeader
        title="Terms of Service"
        description="Operational terms and authorized access guidelines for the BTC-SHIELD platform"
        actions={
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-amber-500/10 border border-amber-500/30 text-amber-500 text-xs font-mono font-medium">
            DRAFT FOR REVIEW
          </div>
        }
      />

      <div className="bg-slate-900 border border-slate-800 rounded-lg p-6 space-y-6 text-sm leading-relaxed text-slate-300">
        <div className="p-3 bg-slate-850 border border-slate-800 rounded text-xs text-slate-400 font-mono">
          STATUS: Draft Document • Operational Scope: Authorized Intelligence & Law Enforcement Forensic Analysis • Version 1.0
        </div>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <ShieldCheck size={18} className="text-blue-500" />
            1. Authorized Purpose & Role-Based Access
          </h2>
          <p>
            BTC-SHIELD is an analytical and forensic platform designed for lawful monitoring, correlation, and anomaly detection of public blockchain transaction traffic and correlated network telemetry. Access is strictly controlled through role-based access control (RBAC):
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-400">
            <li><strong className="text-slate-200">Viewer:</strong> Read-only access to transaction graphs, heuristics, and prioritized alerts.</li>
            <li><strong className="text-slate-200">Analyst:</strong> Analytical exploration, feature inspection, and synthetic testing.</li>
            <li><strong className="text-slate-200">Investigator:</strong> Case dossier creation, investigative notes, and report generation.</li>
            <li><strong className="text-slate-200">Administrator:</strong> User authorization, system configuration, and audit trail verification.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <FileText size={18} className="text-blue-500" />
            2. Data Sources & Forensic Evidence Integrity
          </h2>
          <p>
            All ingested records (CSV, JSON, XML) represent public ledger data or correlated peer network observations. Evidence records generated by the platform incorporate cryptographic SHA-256 hash chains to ensure non-repudiation and prevent retroactive tampering.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100">
            3. Air-Gapped & Offline Deployment
          </h2>
          <p>
            When deployed in Mode A (Offline Air-Gapped Linux Stack), the software operates entirely self-contained without external network egress. No data is transmitted outside the host boundary.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100">
            4. Limitation of Liability
          </h2>
          <p className="text-slate-400 text-xs">
            This system provides probabilistic machine-learning anomaly scores (Isolation Forest, DBSCAN) and deterministic behavioral heuristics. Signals are intended to assist qualified investigators and must be corroborated by human review prior to any operational action.
          </p>
        </section>
      </div>
    </div>
  );
}
